

```{r meta_map, fig.cap="Map of the meta-populations geographical locations and their accept/reject status"}
res_ <- res$meta
if(is.null(input[[paste0("lr_", input$meta)]])) res_ <- res_ %>% mutate(LR_listing = "No")
if(!is.null(input[[paste0("lr_", input$meta)]]))
  res_ <- res_ %>% mutate(LR_listing = ifelse(.[[1]] %in% input[[paste0("lr_",input$meta)]], "Yes", "No"))
res_ <- filter(res_, !(is.na(lat) | is.na(lon))) ## Discard pops with no location
map_plot(res_)
```

### Tables

```{r meta_table}
result_table(res$meta, flat = (params$set_output != "HTML"))
```

### Likelihood ratios

```{r meta_lr}
accepted_ <- if(is.null(input$LR_accept)) FALSE else (input$tilt == "allow")
LR_list(result = res$meta, lr_pops = input$lr_meta, CI = input$CI/100, accepted = accepted_, flat = (params$set_output != "HTML"))
```

## Populations

### Plots

```{r pop_bar_plot, fig.cap="Error bar plots for populations. The bars reflects the approximate confidence interval"}
error_bar_plot(res$pop)
```

```{r pop_map, fig.cap="Map of the populations geographical locations and their accept/reject status"}
res_ <- res$pop
if(is.null(input[[paste0("lr_", input$meta)]])) res_ <- res_ %>% mutate(LR_listing = "No")
if(!is.null(input[[paste0("lr_", input$meta)]]))
  res_ <- res_ %>% mutate(LR_listing = ifelse(.[[1]] %in% input[[paste0("lr_",input$meta)]], "Yes", "No"))
res_ <- filter(res_, !(is.na(lat) | is.na(lon))) ## Discard pops with no location
map_plot(res_)
```

### Tables

```{r pop_table}
result_table(res$pop, flat = (params$set_output != "HTML"))
```

### Likelihood ratios

```{r pop_lr}
LR_list(result = res$pop, lr_pops = input$lr_pop, CI = input$CI/100, accepted = accepted_, flat = (params$set_output != "HTML"))
```

## Appendix

### Uploaded profile

```{r profile, results='asis'}
profile <- Profile() %>% mutate(genotype = paste0(A1, A2)) %>%
  select(locus, genotype)
if(params$set_output == "HTML") profile %>% DT::datatable()
if(params$set_output != "HTML") profile %>% kable()
```
